name: test-docker
on: push
jobs:
  login:
    runs-on: self-hosted
    steps:
      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: registry
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
  build-with-llvm:
    runs-on: self-hosted
    container:
      image: registry/clang-debian11:staging
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Check for files
        run: (ls -alh / && ls -alh /home && ls -alh /opt)
