name: test-docker
on: push
jobs:
  build-with-llvm:
    runs-on: self-hosted
    container:
      image: clang-debian11:staging
      credentials:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Check for files
        run: (ls -alh / && ls -alh /home && ls -alh /opt)
