name: test-docker
on: push
jobs:
  build-with-llvm:
    runs-on: self-hosted
    container:
      image: registry:443/clang-debian11:latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Check for files
        run: (ls -alh / && ls -alh /home && ls -alh /opt)
